### ISSUE TITLE
Errors when running: Cannot read property 'isChatDisabled' and "main" not registered

### ISSUE THREAD

**Issue by nephykoda** [zoom/VideoSDK-ReactNative-Quickstart#1]
**Issue Summary:**
Hi, I am encountering two errors when attempting to run the `react-native-videosdk` library in my React Native project on MacBook Pro M1:

```
ERROR  TypeError: Cannot read property 'isChatDisabled' of null
ERROR  Invariant Violation: "main" has not been registered
```

Also seems to be asked by another user here : https://stackoverflow.com/questions/78313397/zoom-video-sdk-for-react-native-crash-on-import-module

I was able to find a workaround by manually building using XCode for iOS Simulator with Rosetta, but seemingly no solutions for Android atm. 

**Screenshot of Issue**
![error-screenshot](https://github.com/zoom/VideoSDK-ReactNative-Quickstart/assets/93145265/df0b3e27-c0ed-4424-b8f8-9264c87c763a)

**Steps to Reproduce:**
Followed the **Getting Started** instructions in README, on the last step

**Expected Behavior:**
Expected to run the basic quick start project

**Actual Behavior:**
Unable to run for both iOS & Android simulators without any workarounds

**Additional Information:**
- React Native Version: 0.73.6
- `react-native-videosdk` Version: 1.10.10
- Operating System: MacBook Pro M1
- Expo: 50.0.15

**Comment by kashifdroidley3435** [comment]
> Hey, sorry you're facing issues. Have you cloned this repo or are you running a new project? Did you add your Video SDK credentials to `config.ts`?
> 
> Can you confirm if you're using Yarn? What version of cocoapods do have you installed? Did `npx pod-install` run without errors? (I'm using `1.15.2`)
> 
> I'm also running an M1 Pro MacBook and tried installing the dependencies with Yarn, running pod-install and building the app works on both Android emulator and iOS simulator: <img alt="Screenshot 2024-04-23 at 11 00 08 PM" width="1452" src="https://private-user-images.githubusercontent.com/10047883/324933797-a075dfc7-375c-4a3b-a774-5b56e6a29236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjg4NDIsIm5iZiI6MTcxNDAyODU0MiwicGF0aCI6Ii8xMDA0Nzg4My8zMjQ5MzM3OTctYTA3NWRmYzctMzc1Yy00YTNiLWE3NzQtNWI1NmU2YTI5MjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODFiNDhmNGY0MzFmMjFmOGI5MTY2MmJkODVhNjdmMjMwZDFmNTQxYzkzYTM0NGM3M2NjMjJhN2Y5YjQ2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQvhAgpowmdym4ZotuYlTfa3kPvzZyS2ZxlbApMg6LA">

did works the same on windows ? are you able to join video conferencing?

**Comment by EkaanshArora** [comment]
@kashifdroidley3435 you wouldn't be able to build for iOS on windows, but the rest of the steps should be the same to build for Android if you're using windows.

**Comment by nephykoda** [comment]
@EkaanshArora thanks for the response!

After your response, I went to tinker further & managed to get the sample apps to work with some issues:

❌ Not able to run both iOS & Android using `expo start` / `yarn run`
❌ Not able to run both iOS & Android using `expo run:ios` / `yarn ios`
✅ Able to run both iOS Simulator & Android Emulator **using the `expo run:android` script only** 
- i.e. when metro bundler runs, open iOS simulator using `i`

**Questions**
1. Is there anything I need to configure / check to ensure that my `expo start` or `expo run:ios` run as intended as well?
2. Why does `yarn` work but not `npm`? To my understanding - according to the [documentation here](https://developers.zoom.us/docs/video-sdk/react-native/1.10.10/get-started/#2-install-platform-sdk-files), `yarn` is preferred only because it installs the dependency packages in parallel, has better speed & performance.
3. Trying to understand what happens here - is it actually expo pre-building happening so that we are able to utilise the Zoom SDK? I was under the impression that we couldn't do it due to the first paragraph in the [Zoom Video SDK - React Native documentation](https://developers.zoom.us/docs/video-sdk/react-native/1.10.10/get-started/).

---
⚠️ **Errors** - after setting up entirely using Yarn
1. Running `expo run:ios` / `yarn ios`
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:7B9BCBF1-6F2C-4077-8B7B-D681D09B6613, OS:17.4, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:7B9BCBF1-6F2C-4077-8B7B-D681D09B6613, OS:17.4, name:iPhone 15 Pro }
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/nephy/Library/Developer/Xcode/DerivedData/zoomexpo-dvxzwhrtyskllqaivipbywhggyhs/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00019460.sh (in target 'React-rncore' from project 'Pods')
	PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/nephy/Library/Developer/Xcode/DerivedData/zoomexpo-dvxzwhrtyskllqaivipbywhggyhs/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/Script-46EB2E00019490.sh (in target 'hermes-engine' from project 'Pods')
(2 failures)
```

2. Running `expo start` / `yarn start`
- Able to start the Metro Bundler, but running both android & ios simulator hits me with the same errors in my [initial comment](https://github.com/zoom/VideoSDK-ReactNative-Quickstart/issues/1#issue-2242206953)
```
 ERROR  TypeError: Cannot read property 'isChatDisabled' of null, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
› Stopped server
```

---
❓ **Response to your replies**
> Have you cloned this repo or are you running a new project?
- Cloned the repo!

> Can you confirm if you're using Yarn? 
- I had been using `npm` before re-trying using `yarn` after your response

>  Did npx pod-install run without errors?
- `npx pod install` works fine for me
```zsh
npx pod-install                        
Need to install the following packages:
pod-install@0.2.0
Ok to proceed? (y) y
Scanning for pods...
1.15.2
> pod install
Using Expo modules
[Expo] Enabling modular headers for pod ExpoModulesCore
Auto-linking React Native modules for target `zoomexpo`: react-native-pure-jwt and react-native-zoom-video-sdk
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
Analyzing dependencies
[Codegen] Found FBReactNativeSpec
[Codegen] Found rncore
Downloading dependencies
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++20 on /Users/nephy/Developer/VideoSDK-ReactNative-Quickstart/ios/zoomexpo.xcodeproj
Pod install took 6 [s] to run
Integrating client project
expo_patch_react_imports! took 0.073 seconds to transform files.
Pod installation complete! There are 59 dependencies from the Podfile and 62 total pods installed.
```

**Comment by EkaanshArora** [comment]
Hey @nephykoda thanks for following up. Answering questions inline:

> Is there anything I need to configure / check to ensure that my expo start or expo run:ios run as intended as well?

It's hard to say why that is, from the log you posted it can be one of many things like the folder name containing a space, or your node alias might be conflicting, [more here](https://stackoverflow.com/questions/66742033/phasescriptexecution-cp-user-error-in-react-native). Are you using NVM? If yes, do you have node globally installed/aliased?  
Since the project build with the last command you listed, I think it might be due to how you've configured your build environment. Are you able to use these commands in other expo projects? I would suggest removing all the dependencies (both node_modules and pods) and clearing build artifacts then trying again. 
> Why does yarn work but not npm? To my understanding - according to the [documentation here](https://developers.zoom.us/docs/video-sdk/react-native/1.10.10/get-started/#2-install-platform-sdk-files), yarn is preferred only because it installs the dependency packages in parallel, has better speed & performance.

We recommend Yarn same [Expo docs](https://docs.expo.dev/get-started/installation/#recommended-tools). It also let's us use the same package manager to reproduce any errors you face, avoiding having to test the project with different tools. NPM should work also, it's just something we don't test for internally.
> Trying to understand what happens here - is it actually expo pre-building happening so that we are able to utilise the Zoom SDK? I was under the impression that we couldn't do it due to the first paragraph in the [Zoom Video SDK - React Native documentation](https://developers.zoom.us/docs/video-sdk/react-native/1.10.10/get-started/).

Yep, we use Expo prebuild. Since Zoom SDK ships native code, we can't support Expo Go. We use development clients with prebuild.
What's confusing in the doc? We can change the phrasing to make it easier to understand.

**Comment by gorbypark** [comment]
I am running into an issue I think may be related. Basically, if you create a brand new expo project and run `npx expo prebuild` it works.  Then, simply `yarn add @zoom/react-native-videosdk react-native-pure-jwt` and do `npx expo prebuild --clean` and then `npx expo run:ios` and the build will fail with 

```
❌  (ios/Pods/Target Support Files/Pods-appdir/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 |
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/mhamilton/Library/Developer/Xcode/DerivedData/appdir-fyrnbdmxifcphaaldplnpubdxjkc/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import ExpoAsset
  10 | import EXConstants
  11 | import ExpoFileSystem


❌  (ios/Pods/Target Support Files/Pods-appdir/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 |
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/mhamilton/Library/Developer/Xcode/DerivedData/appdir-fyrnbdmxifcphaaldplnpubdxjkc/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import ExpoAsset
  10 | import EXConstants
  11 | import ExpoFileSystem


› 2 error(s), and 0 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
error Command failed with exit code 1.
```

Trying to run the build in Xcode produces a similar error saying you need to choose a target that supports x86
<img width="540" alt="Screenshot 2024-06-17 at 11 22 45 AM" src="https://github.com/zoom/VideoSDK-ReactNative-Quickstart/assets/19569469/55370ec5-23c4-4b22-b84c-8f26d8ee99e8">

going to product->destination->show all destinations and then picking a rosetta based destination and the build works.

Just to be sure, `yarn remove @zoom/react-native-videosdk` and the build works like normal (in a non-rosetta emulator).  I was initially confused because the error is pointing at ExpoModulesCore, but it is 100% sure the react-native-videosdk package triggering this.

**Comment by isaacrmoreno** [comment]
The thing that made the difference for me was reading [EkaanshArora](https://github.com/EkaanshArora) response above where he states, "Since Zoom SDK ships native code, we can't support Expo Go."

Which is where I was trying to build the app initial. @.@

So I would say add the package to your project running: `yarn add @zoom/react-native-videosdk`

Then make a [development build](https://docs.expo.dev/develop/development-builds/create-a-build/), and from there you should be able to get past this error and actually begin developing. Hope this helps anyone else who might come across this.

**Comment by AbrarMehraj** [comment]
I’ve been encountering issues while integrating the Zoom Video SDK in my React Native project. I have followed the provided code from the official GitHub repository and tried multiple SDK versions without success. Specifically, I’m facing the following errors:

TypeError: null is not an object (evaluating ‘RNZoomVideoSdkChatHelper.isChatDisabled’)
This error indicates that the RNZoomVideoSdkChatHelper object is null, which seems to suggest that the Zoom SDK is not being initialized properly.

Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
This occurs repeatedly and points to potential issues with the application’s entry file or improper bundling.

My environment details are as follows:

React Native version: 0.64.4
Development setup: React Native CLI
I have tried several troubleshooting steps, including:

Verifying the Zoom SDK initialization and imports.
Checking the application’s entry file and ensuring proper registration with AppRegistry.
Clearing the cache and rebuilding the project.
Testing different versions of the Zoom SDK.
However, none of these approaches have resolved the issue. Is there any known workaround or specific setup required for using the Zoom SDK with React Native version 0.64.4?

Thank you.
