### ISSUE TITLE
Not able to start the meeting 

### ISSUE THREAD

**Issue by Inzicoder** [zoom/videosdk-reactnative-quickstart#5]
I am trying to start the meeting but there is no response after I click on join meeting button , I am not getting any error either.

**Comment by EkaanshArora** [comment]
Hey it's difficult to debug this issue without more information.
Did you follow the steps in the readme? Did you use your own Video SDK key and secret? 
Can you share a code snippet or some logs?

**Comment by EkaanshArora** [comment]
From: https://developers.zoom.us/docs/video-sdk/android/error-codes/
Name | Error Code | Description | Suggestion
-- | -- | -- | --
Errors_Session_Invalid_Param | 2014 | Received invalid parameters of join Session. | Please double check the parameters you passed to the method and try again

Please double check the parameters you passed to the method and try again. Usually this happens when you are using incorrect credentials.
Did you get the correct Video SDK credentials? Are you using the same sessionName in the JWT and the joinSession call?

**Comment by jagdishky** [comment]
> I am trying to start the meeting but there is no response after I click on join meeting button , I am not getting any error either.

Same here I also trying to start the meeting but there is not response and not even getting any error. Do have find any solution for that?
